version: 0.0
os: linux
files:
  - source: target/demo-0.0.1-SNAPSHOT.war
    destination: /var/lib/tomcat8/webapps/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

#version: 0.0
#os: linux
#files:
#  - source: /index.html
#    destination: /var/www/html/
#hooks:
#  BeforeInstall:
#    - location: scripts/install_dependencies
#      timeout: 300
#      runas: root
#    - location: scripts/start_server
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root