# This file controls the AWS CodeBuild
version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn install
  post_build:
    commands:
      - echo "Entered the post-build phase"
artifacts:
  files:
    - 'target/demo-0.0.1-SNAPSHOT.war'
    - 'appspec.yml'
    - 'scripts/*'